---
- name: Configure VPN Server
  hosts: vpn
  vars_files:
    - secrets.yml
  vars:
    ansible_host: "{{ VPN_HOST }}"
  roles:
    - vpn

# - name: Configure Monitoring
#   hosts: monitoring
#   roles:
#     - monitoring

- name: Configure DNS Server
  hosts: dns
  vars_files:
    - secrets.yml
  vars:
    ansible_host: "{{ DNS_HOST }}"
  roles:
    - dns

- name: Configure External Host
  hosts: external
  vars_files:
    - secrets.yml
  vars:
    ansible_host: "{{ EXTERNAL_HOST }}"
  pre_tasks:
    - name: Set fact
      ansible.builtin.set_fact:
        ansible_host: "{{ EXTERNAL_HOST }}"
  roles:
    - external

- name: Configure Internal Host
  hosts: internal
  vars_files:
    - secrets.yml
  vars:
    ansible_host: "{{ INTERNAL_HOST }}"
  roles:
    - internal

- name: Configure VPS Host
  hosts: vps
  vars_files:
    - secrets.yml
  vars:
    ansible_host: "{{ VPS_HOST }}"
  roles:
    - vps
