---
- name: Ensure Jellyfin is running
  community.docker.docker_container:
    name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    env:
      PUID: "{{ UID | string }}"
      PGID: "{{ GID | string }}"
      TZ: "{{ TIME_ZONE }}"
    volumes:
      - "{{ PLEX_MOUNT_1 }}"
      - "{{ PLEX_MOUNT_2 }}"
      - "{{ PLEX_MOUNT_3 }}"
      - "{{ PLEX_MOUNT_4 }}"
      - "{{ CFG_MOUNT }}/jellyfin-cfg:/config"
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    restart_policy: always
  notify: Restart Jellyfin Container
