---
- name: Set DNS server for systemd-resolved
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^#?DNS="
    line: "DNS={{ DNS_HOST }}"
    state: present
  become: true

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  become: true

- name: Link resolv.conf to systemd-resolved
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - wireguard
      - ufw
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Allow SSH access through UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Enable ufw
  community.general.ufw:
    state: enabled
  become: true

- name: Configure WireGuard
  ansible.builtin.template:
    src: wireguard.conf.j2
    dest: /etc/wireguard/wg0.conf
  notify:
    - Restart WireGuard
  become: true

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
