---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install necessary packages
  apt:
    name:
      - bind9
      - ufw
    state: present
  become: yes

- name: Allow DNS traffic (UDP/53)
  ufw:
    rule: allow
    port: '53'
    proto: udp
  become: yes

- name: Allow DNS traffic (TCP/53) - for zone transfers and larger queries
  ufw:
    rule: allow
    port: '53'
    proto: tcp
  become: yes

- name: Allow SSH traffic
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  become: yes

- name: Enable ufw
  ufw:
    state: enabled
  become: yes

- name: Configure named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: '0644'
  become: yes

- name: Configure named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: bind
    group: bind
    mode: '0644'
  become: yes

- name: Ensure /etc/bind/zones directory exists
  file:
    path: /etc/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: '0750'
  become: yes

- name: Create zone file for {{ DNS_DOMAIN }}
  template:
    src: db.domain.j2
    dest: "/etc/bind/zones/db.{{ DNS_DOMAIN }}"
    owner: bind
    group: bind
    mode: '0644'
  vars:
    serial: "{{ lookup('pipe', 'date +%s') }}"    
  become: yes
  notify: Restart BIND

- name: Check if wireguard route exists
  ansible.builtin.command: ip route show {{ WG_NETWORK }} via {{ VPN_HOST }} dev ens18 proto static
  register: route_check
  ignore_errors: yes
  become: yes

- name: Add route to wireguard network if not exists
  ansible.builtin.command: ip route add {{ WG_NETWORK }}  via {{ VPN_HOST }} dev ens18 proto static onlink
  when: route_check.rc != 0
  become: yes

  