---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - bind9
      - ufw
    state: present
  become: true

- name: Allow DNS traffic (UDP/53)
  community.general.ufw:
    rule: allow
    port: "53"
    proto: udp
  become: true

- name: Allow DNS traffic (TCP/53) - for zone transfers and larger queries
  community.general.ufw:
    rule: allow
    port: "53"
    proto: tcp
  become: true

- name: Allow SSH traffic
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp
  become: true

- name: Enable ufw
  community.general.ufw:
    state: enabled
  become: true

- name: Configure named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: "0644"
  become: true

- name: Configure named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: bind
    group: bind
    mode: "0644"
  become: true

- name: Ensure /etc/bind/zones directory exists
  ansible.builtin.file:
    path: /etc/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: "0750"
  become: true

- name: Create zone file for {{ DNS_DOMAIN }}
  ansible.builtin.template:
    src: db.domain.j2
    dest: "/etc/bind/zones/db.{{ DNS_DOMAIN }}"
    owner: bind
    group: bind
    mode: "0644"
  vars:
    serial: "{{ lookup('pipe', 'date +%s') }}"
  become: true
  notify: Restart BIND

- name: Check if wireguard route exists
  ansible.builtin.command: ip route show {{ WG_NETWORK }} via {{ VPN_HOST }} dev ens18 proto static
  register: route_check
  ignore_errors: true
  become: true

- name: Add route to wireguard network if not exists
  ansible.builtin.command: ip route add {{ WG_NETWORK }}  via {{ VPN_HOST }} dev ens18 proto static onlink
  when: route_check.rc != 0
  become: true
