---
- name: Check NFS directories
  ansible.builtin.stat:
    path: "{{ item.dest }}"
  loop: "{{ NFS_MOUNTS }}"
  register: dir_status

- name: Create NFS directories if missing
  ansible.builtin.file:
    path: "{{ item.item.dest }}"
    state: directory
    mode: "0755"
  loop: "{{ dir_status.results }}"
  when: not item.stat.exists
  become: true  

- name: Ensure /etc/fstab entries for NFS
  ansible.builtin.blockinfile:
    path: /etc/fstab
    block: |
      {% for MOUNT in NFS_MOUNTS %}
      {{ NFS_SERVER }}:{{ MOUNT.source }} {{ MOUNT.dest }} nfs {{ MOUNT.options }} 0 0
      {% endfor %}
  become: true      

- name: Mount NFS shares (with DNS retry)
  block:
    - name: Mount share
      ansible.posix.mount:
        path: "{{ item.dest }}"
        src: "{{ NFS_SERVER }}:{{ item.source }}"
        fstype: nfs
        opts: "{{ item.options | default('defaults') }}"
        state: mounted
      loop: "{{ NFS_MOUNTS }}"
      register: mount_results
      become: true      
  rescue:
    - name: Restart systemd-resolved on DNS hiccup
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: restarted
      become: true        

    - name: Retry mounting
      ansible.posix.mount:
        path: "{{ item.dest }}"
        src: "{{ NFS_SERVER }}:{{ item.source }}"
        fstype: nfs
        opts: "{{ item.options | default('defaults') }}"
        state: mounted
      loop: "{{ NFS_MOUNTS }}"
      register: mount_retry
      failed_when: mount_retry.failed
      become: true